// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kakndhltpzyahijcidit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtha25kaGx0cHp5YWhpamNpZGl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyMzk4NzIsImV4cCI6MjA4NDgxNTg3Mn0.LD3A1obvRdBXtFdVLbQfJttH6mBJIlFjB-14sZj7kzY";

// Create a typed schema without internal properties
type PublicSchema = Database['public'];

type TypedDatabase = {
  public: PublicSchema;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: SupabaseClient<TypedDatabase> = createClient<TypedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
